# Project: Проект1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "../Program\ 13/main.o"
LINKOBJ  = "../Program 13/main.o"
LIBS     = -L"M:/File/App/Dev-Cpp/MinGW64/lib" -L"M:/File/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"M:/File/App/Dev-Cpp/MinGW64/include" -I"M:/File/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"M:/File/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"M:/File/App/Dev-Cpp/MinGW64/include" -I"M:/File/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"M:/File/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"M:/File/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = project12.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"../Program\ 13/main.o": ../Program\ 13/main.cpp
	$(CPP) -c "../Program 13/main.cpp" -o "../Program 13/main.o" $(CXXFLAGS)
